//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibaryToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoLibaryToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} with {1} extension.
        /// </summary>
        internal static string MediaMinerBase_GetMediaFilesList_Found__0__with__1__extension {
            get {
                return ResourceManager.GetString("MediaMinerBase_GetMediaFilesList_Found__0__with__1__extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get date from {0}. Error: {1}.
        /// </summary>
        internal static string MediaMinerBase_GetTakenDateEntry_Cannot_get_date_from__0___Error___1_ {
            get {
                return ResourceManager.GetString("MediaMinerBase_GetTakenDateEntry_Cannot_get_date_from__0___Error___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}/{1}.
        /// </summary>
        internal static string MediaMinerBase_GetTakenDateEntry_Processed__0___1_ {
            get {
                return ResourceManager.GetString("MediaMinerBase_GetTakenDateEntry_Processed__0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Toolkit_CloneModificationDates_Error___0_ {
            get {
                return ResourceManager.GetString("Toolkit_CloneModificationDates_Error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} files.
        /// </summary>
        internal static string Toolkit_CloneModificationDates_Found__0__files {
            get {
                return ResourceManager.GetString("Toolkit_CloneModificationDates_Found__0__files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified {0} files.
        /// </summary>
        internal static string Toolkit_CloneModificationDates_Modified__0__files {
            get {
                return ResourceManager.GetString("Toolkit_CloneModificationDates_Modified__0__files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} from {1} to {2}.
        /// </summary>
        internal static string Toolkit_CloneModificationDates_Updating__0__from__1__to__2_ {
            get {
                return ResourceManager.GetString("Toolkit_CloneModificationDates_Updating__0__from__1__to__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Toolkit_OrganizePhotoLibrary_Cancelled {
            get {
                return ResourceManager.GetString("Toolkit_OrganizePhotoLibrary_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating unique file names for {0} duplicates.
        /// </summary>
        internal static string Toolkit_OrganizePhotoLibrary_Creating_unique_file_names_for__0__duplicates {
            get {
                return ResourceManager.GetString("Toolkit_OrganizePhotoLibrary_Creating_unique_file_names_for__0__duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming: {0}.
        /// </summary>
        internal static string Toolkit_OrganizePhotoLibrary_Error_renaming___0_ {
            get {
                return ResourceManager.GetString("Toolkit_OrganizePhotoLibrary_Error_renaming___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded info for {0} photos.
        /// </summary>
        internal static string Toolkit_OrganizePhotoLibrary_Loaded_info_for__0__photos {
            get {
                return ResourceManager.GetString("Toolkit_OrganizePhotoLibrary_Loaded_info_for__0__photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded info for {0} videos.
        /// </summary>
        internal static string Toolkit_OrganizePhotoLibrary_Loaded_info_for__0__videos {
            get {
                return ResourceManager.GetString("Toolkit_OrganizePhotoLibrary_Loaded_info_for__0__videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed {0} files, skipped {1}.
        /// </summary>
        internal static string Toolkit_OrganizePhotoLibrary_Renamed__0__files__skipped__1_ {
            get {
                return ResourceManager.GetString("Toolkit_OrganizePhotoLibrary_Renamed__0__files__skipped__1_", resourceCulture);
            }
        }
    }
}
